# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Disable sleep temporarily so keyboard never shuts down while pairing
CONFIG_ZMK_SLEEP=n

# Bluetooth signal power boost
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# macOS BLE connection fix
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Explicit keyboard name
CONFIG_ZMK_KEYBOARD_NAME="Corne"
CONFIG_ZMK_BLE=n
